import React, { useLayoutEffect, useMemo, useRef } from "react";
import * as THREE from "three";
import { useThree } from "@react-three/fiber";
import {
  AbsoluteFill,
  Video,
  getRemotionEnvironment,
  staticFile,
  useVideoConfig,
} from "remotion";
import {
  ThreeCanvas,
  useOffthreadVideoTexture,
  useVideoTexture,
} from "@remotion/three";
import { fragmentShader, vertexShader } from "./duotonePopShader";

/**
 * A flat, graphic "cutout" look: the background renders as one solid color
 * (white by default), separated from the rest by the same precomputed
 * person-segmentation matte the other compositions use (public/mask*.mp4,
 * generated by scripts/generate-mask.js) — no shading, no gradient.
 *
 * The foreground subject can be either the ORIGINAL video, untouched (pass
 * `foregroundColor: "original"`, the default) or another flat color for a
 * true two-tone look (e.g. "#FF0000").
 */
export type DuotonePopProps = {
  src: string;
  maskSrc: string;
  /** CSS hex color for the foreground, e.g. "#FF0000" — or the literal string "original" to keep the subject's real video colors untouched. */
  foregroundColor: string;
  /** CSS hex color for the background, e.g. "#FFFFFF". */
  backgroundColor: string;
};

export const defaultDuotonePopProps: Omit<
  DuotonePopProps,
  "src" | "maskSrc"
> = {
  foregroundColor: "original",
  backgroundColor: "#FFFFFF",
};

function hexToRgb01(hex: string): [number, number, number] {
  const clean = hex.replace("#", "");
  const r = parseInt(clean.substring(0, 2), 16) / 255;
  const g = parseInt(clean.substring(2, 4), 16) / 255;
  const b = parseInt(clean.substring(4, 6), 16) / 255;
  return [r, g, b];
}

const ShaderPlane: React.FC<{
  colorTexture: THREE.Texture;
  maskTexture: THREE.Texture;
  params: Omit<DuotonePopProps, "src" | "maskSrc">;
}> = ({ colorTexture, maskTexture, params }) => {
  const advance = useThree((state) => state.advance);
  const { isRendering } = getRemotionEnvironment();

  const material = useMemo(
    () =>
      new THREE.ShaderMaterial({
        vertexShader,
        fragmentShader,
        uniforms: {
          uColorTexture: { value: null as THREE.Texture | null },
          uMaskTexture: { value: null as THREE.Texture | null },
          uForegroundColor: { value: new THREE.Vector3(1, 0, 0) },
          uBackgroundColor: { value: new THREE.Vector3(1, 1, 1) },
          uUseOriginalForeground: { value: 1 },
        },
      }),
    [],
  );

  material.uniforms.uColorTexture.value = colorTexture;
  material.uniforms.uMaskTexture.value = maskTexture;

  const useOriginal = params.foregroundColor === "original";
  material.uniforms.uUseOriginalForeground.value = useOriginal ? 1 : 0;
  const [fr, fg, fb] = useOriginal
    ? [0, 0, 0]
    : hexToRgb01(params.foregroundColor);
  material.uniforms.uForegroundColor.value.set(fr, fg, fb);

  const [br, bg, bb] = hexToRgb01(params.backgroundColor);
  material.uniforms.uBackgroundColor.value.set(br, bg, bb);

  // See SelectiveDesaturation.tsx for why this manual advance is necessary:
  // <ThreeCanvas> draws once per frame change, but the async video textures
  // resolve after that draw during rendering, so we force a second draw.
  useLayoutEffect(() => {
    if (isRendering) {
      advance(performance.now());
    }
  });

  return (
    <mesh frustumCulled={false}>
      <planeGeometry args={[2, 2]} />
      <primitive object={material} attach="material" />
    </mesh>
  );
};

const RenderScene: React.FC<{
  src: string;
  maskSrc: string;
  params: Omit<DuotonePopProps, "src" | "maskSrc">;
}> = ({ src, maskSrc, params }) => {
  const colorTexture = useOffthreadVideoTexture({ src });
  const maskTexture = useOffthreadVideoTexture({ src: maskSrc });
  if (!colorTexture || !maskTexture) {
    return null;
  }
  return (
    <ShaderPlane
      colorTexture={colorTexture}
      maskTexture={maskTexture}
      params={params}
    />
  );
};

const PreviewScene: React.FC<{
  src: string;
  maskSrc: string;
  width: number;
  height: number;
  params: Omit<DuotonePopProps, "src" | "maskSrc">;
}> = ({ src, maskSrc, width, height, params }) => {
  const colorRef = useRef<HTMLVideoElement>(null);
  const maskRef = useRef<HTMLVideoElement>(null);
  const colorTexture = useVideoTexture(colorRef);
  const maskTexture = useVideoTexture(maskRef);
  return (
    <>
      <Video
        ref={colorRef}
        src={src}
        muted
        style={{ position: "absolute", opacity: 0, width: 1, height: 1 }}
      />
      <Video
        ref={maskRef}
        src={maskSrc}
        muted
        style={{ position: "absolute", opacity: 0, width: 1, height: 1 }}
      />
      {colorTexture && maskTexture ? (
        <ThreeCanvas width={width} height={height}>
          <ShaderPlane
            colorTexture={colorTexture}
            maskTexture={maskTexture}
            params={params}
          />
        </ThreeCanvas>
      ) : null}
    </>
  );
};

export const DuotonePop: React.FC<DuotonePopProps> = ({
  src,
  maskSrc,
  ...params
}) => {
  const { width, height } = useVideoConfig();
  const resolvedSrc = src.startsWith("http") ? src : staticFile(src);
  const resolvedMaskSrc = maskSrc.startsWith("http")
    ? maskSrc
    : staticFile(maskSrc);
  const isRendering = getRemotionEnvironment().isRendering;

  return (
    <AbsoluteFill style={{ backgroundColor: "black" }}>
      {isRendering ? (
        <ThreeCanvas width={width} height={height}>
          <RenderScene src={resolvedSrc} maskSrc={resolvedMaskSrc} params={params} />
        </ThreeCanvas>
      ) : (
        <PreviewScene
          src={resolvedSrc}
          maskSrc={resolvedMaskSrc}
          width={width}
          height={height}
          params={params}
        />
      )}
    </AbsoluteFill>
  );
};
