import React, { useLayoutEffect, useMemo, useRef } from "react";
import * as THREE from "three";
import { useThree } from "@react-three/fiber";
import {
  AbsoluteFill,
  Video,
  getRemotionEnvironment,
  staticFile,
  useVideoConfig,
} from "remotion";
import {
  ThreeCanvas,
  useOffthreadVideoTexture,
  useVideoTexture,
} from "@remotion/three";
import { fragmentShader, vertexShader } from "./duotonePopShader";

/**
 * A flat, graphic two-color look: the foreground subject renders as one
 * solid color, the background as another — a simple, bold contrast rather
 * than a color grade. Uses the same precomputed person-segmentation matte as
 * ForegroundPop (public/mask*.mp4, generated by scripts/generate-mask.js),
 * but doesn't sample the color video at all — both colors are flat
 * constants, so only the mask's shape matters.
 */
export type DuotonePopProps = {
  maskSrc: string;
  /** CSS hex color for the foreground (subject), e.g. "#FF0000". */
  foregroundColor: string;
  /** CSS hex color for the background, e.g. "#FFFFFF". */
  backgroundColor: string;
};

export const defaultDuotonePopProps: Omit<DuotonePopProps, "maskSrc"> = {
  foregroundColor: "#FF0000",
  backgroundColor: "#FFFFFF",
};

function hexToRgb01(hex: string): [number, number, number] {
  const clean = hex.replace("#", "");
  const r = parseInt(clean.substring(0, 2), 16) / 255;
  const g = parseInt(clean.substring(2, 4), 16) / 255;
  const b = parseInt(clean.substring(4, 6), 16) / 255;
  return [r, g, b];
}

const ShaderPlane: React.FC<{
  maskTexture: THREE.Texture;
  params: Omit<DuotonePopProps, "maskSrc">;
}> = ({ maskTexture, params }) => {
  const advance = useThree((state) => state.advance);
  const { isRendering } = getRemotionEnvironment();

  const material = useMemo(
    () =>
      new THREE.ShaderMaterial({
        vertexShader,
        fragmentShader,
        uniforms: {
          uMaskTexture: { value: null as THREE.Texture | null },
          uForegroundColor: { value: new THREE.Vector3(1, 0, 0) },
          uBackgroundColor: { value: new THREE.Vector3(1, 1, 1) },
        },
      }),
    [],
  );

  material.uniforms.uMaskTexture.value = maskTexture;
  const [fr, fg, fb] = hexToRgb01(params.foregroundColor);
  const [br, bg, bb] = hexToRgb01(params.backgroundColor);
  material.uniforms.uForegroundColor.value.set(fr, fg, fb);
  material.uniforms.uBackgroundColor.value.set(br, bg, bb);

  // See SelectiveDesaturation.tsx for why this manual advance is necessary:
  // <ThreeCanvas> draws once per frame change, but the async video texture
  // resolves after that draw during rendering, so we force a second draw.
  useLayoutEffect(() => {
    if (isRendering) {
      advance(performance.now());
    }
  });

  return (
    <mesh frustumCulled={false}>
      <planeGeometry args={[2, 2]} />
      <primitive object={material} attach="material" />
    </mesh>
  );
};

const RenderScene: React.FC<{
  maskSrc: string;
  params: Omit<DuotonePopProps, "maskSrc">;
}> = ({ maskSrc, params }) => {
  const maskTexture = useOffthreadVideoTexture({ src: maskSrc });
  if (!maskTexture) {
    return null;
  }
  return <ShaderPlane maskTexture={maskTexture} params={params} />;
};

const PreviewScene: React.FC<{
  maskSrc: string;
  width: number;
  height: number;
  params: Omit<DuotonePopProps, "maskSrc">;
}> = ({ maskSrc, width, height, params }) => {
  const maskRef = useRef<HTMLVideoElement>(null);
  const maskTexture = useVideoTexture(maskRef);
  return (
    <>
      <Video
        ref={maskRef}
        src={maskSrc}
        muted
        style={{ position: "absolute", opacity: 0, width: 1, height: 1 }}
      />
      {maskTexture ? (
        <ThreeCanvas width={width} height={height}>
          <ShaderPlane maskTexture={maskTexture} params={params} />
        </ThreeCanvas>
      ) : null}
    </>
  );
};

export const DuotonePop: React.FC<DuotonePopProps> = ({
  maskSrc,
  ...params
}) => {
  const { width, height } = useVideoConfig();
  const resolvedMaskSrc = maskSrc.startsWith("http")
    ? maskSrc
    : staticFile(maskSrc);
  const isRendering = getRemotionEnvironment().isRendering;

  return (
    <AbsoluteFill style={{ backgroundColor: "black" }}>
      {isRendering ? (
        <ThreeCanvas width={width} height={height}>
          <RenderScene maskSrc={resolvedMaskSrc} params={params} />
        </ThreeCanvas>
      ) : (
        <PreviewScene
          maskSrc={resolvedMaskSrc}
          width={width}
          height={height}
          params={params}
        />
      )}
    </AbsoluteFill>
  );
};
