import React, { useLayoutEffect, useMemo, useRef } from "react";
import * as THREE from "three";
import { useThree } from "@react-three/fiber";
import {
  AbsoluteFill,
  Video,
  getRemotionEnvironment,
  staticFile,
  useCurrentFrame,
  useVideoConfig,
} from "remotion";
import {
  ThreeCanvas,
  useOffthreadVideoTexture,
  useVideoTexture,
} from "@remotion/three";
import { fragmentShader, vertexShader } from "./foregroundPopShader";

/**
 * Boosts saturation/brightness on the foreground subject (kept pixel-sharp)
 * and recolors + boosts the background toward a per-frame COMPLEMENTARY hue,
 * so both regions read as vivid but visibly different colors — the contrast
 * comes from color, not from one side being desaturated. The background is
 * also gently liquified (animated UV warp) so it reads as a distinct, moving
 * field behind the subject.
 *
 * The complementary hue is computed ahead of time per frame from the ACTUAL
 * dominant color of the foreground in that shot (see
 * scripts/generate-mask.js -> src/data/scene-colors*.json), so which color
 * the background pops in adapts to the footage instead of being hardcoded.
 * That per-frame array is passed in as `backgroundHues` (imported from the
 * right scene-colors*.json in Root.tsx) rather than hardcoded here, since
 * each source video needs its own.
 *
 * Uses a precomputed person-segmentation matte (public/mask*.mp4, generated
 * by the same script) instead of a color-based mask. See README.md for how
 * to regenerate both if you swap in a different source video.
 */
export type ForegroundPopProps = {
  src: string;
  maskSrc: string;
  /** Per-frame background target hue in degrees, e.g. imported from a scene-colors*.json generated by scripts/generate-mask.js. */
  backgroundHues: number[];
  /** Foreground saturation multiplier. 1 = unchanged, >1 = more vivid. */
  foregroundSaturation: number;
  /** Foreground brightness multiplier. 1 = unchanged, >1 = brighter. */
  foregroundBrightness: number;
  /** Background saturation multiplier. 1 = unchanged, >1 = more vivid too. */
  backgroundSaturation: number;
  /** Background brightness multiplier. 1 = unchanged, <1 = dimmer. */
  backgroundBrightness: number;
  /** How hard to pull the background's hue toward the per-frame complementary target. 0 = leave its own hue alone, 1 = fully replace it. */
  backgroundColorizeStrength: number;
  /** Liquify warp displacement, in UV units. ~0.01-0.02 reads as a subtle ripple. */
  liquifyAmount: number;
  /** Spatial frequency of the liquify ripples. */
  liquifyScale: number;
  /** Animation speed multiplier for the liquify effect. */
  liquifySpeed: number;
};

/**
 * Sensible defaults: subject pops, background is vivid in a contrasting
 * color and gently liquified — dialed to ~60% intensity (each multiplier's
 * departure from "neutral" is scaled to 60% of its original full-strength
 * value; see README.md for the full-strength numbers).
 */
export const defaultForegroundPopProps: Omit<
  ForegroundPopProps,
  "src" | "maskSrc" | "backgroundHues"
> = {
  foregroundSaturation: 1.15,
  foregroundBrightness: 1.05,
  backgroundSaturation: 1.09,
  backgroundBrightness: 0.95,
  backgroundColorizeStrength: 0.48,
  liquifyAmount: 0.0072,
  liquifyScale: 8,
  liquifySpeed: 0.8,
};

const ShaderPlane: React.FC<{
  colorTexture: THREE.Texture;
  maskTexture: THREE.Texture;
  backgroundTargetHueDeg: number;
  time: number;
  params: Omit<ForegroundPopProps, "src" | "maskSrc" | "backgroundHues">;
}> = ({ colorTexture, maskTexture, backgroundTargetHueDeg, time, params }) => {
  const advance = useThree((state) => state.advance);
  const { isRendering } = getRemotionEnvironment();

  const material = useMemo(
    () =>
      new THREE.ShaderMaterial({
        vertexShader,
        fragmentShader,
        uniforms: {
          uColorTexture: { value: null as THREE.Texture | null },
          uMaskTexture: { value: null as THREE.Texture | null },
          uForegroundSaturation: { value: 1 },
          uForegroundBrightness: { value: 1 },
          uBackgroundSaturation: { value: 1 },
          uBackgroundBrightness: { value: 1 },
          uBackgroundTargetHue: { value: 0 },
          uBackgroundColorizeStrength: { value: 0 },
          uTime: { value: 0 },
          uLiquifyAmount: { value: 0 },
          uLiquifyScale: { value: 1 },
          uLiquifySpeed: { value: 1 },
        },
      }),
    [],
  );

  material.uniforms.uColorTexture.value = colorTexture;
  material.uniforms.uMaskTexture.value = maskTexture;
  material.uniforms.uForegroundSaturation.value = params.foregroundSaturation;
  material.uniforms.uForegroundBrightness.value = params.foregroundBrightness;
  material.uniforms.uBackgroundSaturation.value = params.backgroundSaturation;
  material.uniforms.uBackgroundBrightness.value = params.backgroundBrightness;
  material.uniforms.uBackgroundTargetHue.value = backgroundTargetHueDeg;
  material.uniforms.uBackgroundColorizeStrength.value =
    params.backgroundColorizeStrength;
  material.uniforms.uTime.value = time;
  material.uniforms.uLiquifyAmount.value = params.liquifyAmount;
  material.uniforms.uLiquifyScale.value = params.liquifyScale;
  material.uniforms.uLiquifySpeed.value = params.liquifySpeed;

  // See SelectiveDesaturation.tsx for why this manual advance is necessary:
  // <ThreeCanvas> draws once per frame change, but the async video textures
  // resolve after that draw during rendering, so we force a second draw.
  useLayoutEffect(() => {
    if (isRendering) {
      advance(performance.now());
    }
  });

  return (
    <mesh frustumCulled={false}>
      <planeGeometry args={[2, 2]} />
      <primitive object={material} attach="material" />
    </mesh>
  );
};

const RenderScene: React.FC<{
  src: string;
  maskSrc: string;
  backgroundTargetHueDeg: number;
  time: number;
  params: Omit<ForegroundPopProps, "src" | "maskSrc" | "backgroundHues">;
}> = ({ src, maskSrc, backgroundTargetHueDeg, time, params }) => {
  const colorTexture = useOffthreadVideoTexture({ src });
  const maskTexture = useOffthreadVideoTexture({ src: maskSrc });
  if (!colorTexture || !maskTexture) {
    return null;
  }
  return (
    <ShaderPlane
      colorTexture={colorTexture}
      maskTexture={maskTexture}
      backgroundTargetHueDeg={backgroundTargetHueDeg}
      time={time}
      params={params}
    />
  );
};

const PreviewScene: React.FC<{
  src: string;
  maskSrc: string;
  width: number;
  height: number;
  backgroundTargetHueDeg: number;
  time: number;
  params: Omit<ForegroundPopProps, "src" | "maskSrc" | "backgroundHues">;
}> = ({ src, maskSrc, width, height, backgroundTargetHueDeg, time, params }) => {
  const colorRef = useRef<HTMLVideoElement>(null);
  const maskRef = useRef<HTMLVideoElement>(null);
  const colorTexture = useVideoTexture(colorRef);
  const maskTexture = useVideoTexture(maskRef);
  return (
    <>
      <Video
        ref={colorRef}
        src={src}
        muted
        style={{ position: "absolute", opacity: 0, width: 1, height: 1 }}
      />
      <Video
        ref={maskRef}
        src={maskSrc}
        muted
        style={{ position: "absolute", opacity: 0, width: 1, height: 1 }}
      />
      {colorTexture && maskTexture ? (
        <ThreeCanvas width={width} height={height}>
          <ShaderPlane
            colorTexture={colorTexture}
            maskTexture={maskTexture}
            backgroundTargetHueDeg={backgroundTargetHueDeg}
            time={time}
            params={params}
          />
        </ThreeCanvas>
      ) : null}
    </>
  );
};

export const ForegroundPop: React.FC<ForegroundPopProps> = ({
  src,
  maskSrc,
  backgroundHues,
  ...params
}) => {
  const { width, height, fps } = useVideoConfig();
  const frame = useCurrentFrame();
  const resolvedSrc = src.startsWith("http") ? src : staticFile(src);
  const resolvedMaskSrc = maskSrc.startsWith("http")
    ? maskSrc
    : staticFile(maskSrc);
  const isRendering = getRemotionEnvironment().isRendering;

  const backgroundTargetHueDeg =
    backgroundHues[Math.min(frame, backgroundHues.length - 1)] ?? 210;
  const time = frame / fps;

  return (
    <AbsoluteFill style={{ backgroundColor: "black" }}>
      {isRendering ? (
        <ThreeCanvas width={width} height={height}>
          <RenderScene
            src={resolvedSrc}
            maskSrc={resolvedMaskSrc}
            backgroundTargetHueDeg={backgroundTargetHueDeg}
            time={time}
            params={params}
          />
        </ThreeCanvas>
      ) : (
        <PreviewScene
          src={resolvedSrc}
          maskSrc={resolvedMaskSrc}
          width={width}
          height={height}
          backgroundTargetHueDeg={backgroundTargetHueDeg}
          time={time}
          params={params}
        />
      )}
    </AbsoluteFill>
  );
};
