import React, { useLayoutEffect, useMemo, useRef } from "react";
import * as THREE from "three";
import { useThree } from "@react-three/fiber";
import {
  AbsoluteFill,
  Video,
  getRemotionEnvironment,
  staticFile,
  useCurrentFrame,
  useVideoConfig,
} from "remotion";
import {
  ThreeCanvas,
  useOffthreadVideoTexture,
  useVideoTexture,
} from "@remotion/three";
import { fragmentShader, vertexShader } from "./foregroundPopShader";

/**
 * Boosts saturation/brightness on the foreground subject (kept pixel-sharp)
 * and recolors the background toward a per-frame COMPLEMENTARY hue — the
 * exact opposite side of the color wheel from the subject's own dominant
 * color in that shot, computed ahead of time by scripts/generate-mask.js and
 * looked up per frame via the `backgroundHues` prop (see Root.tsx) — so a
 * pink outfit pushes the background toward green, a blue one toward orange,
 * and so on, automatically. It's also gently liquified (animated UV warp) so
 * it reads as a distinct, moving field behind the crisp subject.
 *
 * The background's saturation and brightness are each blended TOWARD A FIXED
 * TARGET (not multiplied by the source pixel's own values, see
 * foregroundPopShader.ts) so the effect's visible STRENGTH is consistent
 * across different clips, even though the HUE it lands on varies per scene.
 * An earlier multiplicative version looked barely-there on flat/dark footage
 * and blown-out on already-vivid, brightly-lit footage, because multiplying
 * preserves whatever the source happened to be; blending toward a fixed
 * saturation/brightness target instead makes every clip converge on the same
 * intensity at the same `backgroundColorizeStrength`.
 *
 * Uses a precomputed person-segmentation matte (public/mask*.mp4, generated
 * by the same script) instead of a color-based mask. See README.md for how
 * to regenerate both if you swap in a different source video.
 */
export type ForegroundPopProps = {
  src: string;
  maskSrc: string;
  /** Per-frame background target hue in degrees, imported from a scene-colors*.json generated by scripts/generate-mask.js. */
  backgroundHues: number[];
  /** Foreground saturation multiplier. 1 = unchanged, >1 = more vivid. */
  foregroundSaturation: number;
  /** Foreground brightness multiplier. 1 = unchanged, >1 = brighter. */
  foregroundBrightness: number;
  /** Target saturation the background is pulled toward (same for every clip, regardless of source vividness). */
  backgroundTargetSaturation: number;
  /** Target brightness (HSV value) the background is pulled toward (same for every clip). */
  backgroundTargetBrightness: number;
  /** How strongly to pull the background's hue/saturation/brightness toward its per-frame target. 0 = leave the background untouched, 1 = fully replace it, regardless of the source footage. */
  backgroundColorizeStrength: number;
  /** Liquify warp displacement, in UV units. ~0.005-0.01 reads as a gentle drift. */
  liquifyAmount: number;
  /** Spatial frequency of the liquify ripples — lower = bigger, cloudier shapes. */
  liquifyScale: number;
  /** Animation speed multiplier for the liquify effect. */
  liquifySpeed: number;
};

/**
 * Sensible defaults: subject pops with a modest, consistent saturation/
 * brightness boost; background is pulled toward its own per-frame
 * complementary hue at a fixed, consistent saturation/brightness — vivid but
 * not neon — plus a gentle liquify, so the "different color, still vivid"
 * contrast reads the same way on every clip regardless of how saturated or
 * bright the source footage originally was.
 */
export const defaultForegroundPopProps: Omit<
  ForegroundPopProps,
  "src" | "maskSrc" | "backgroundHues"
> = {
  foregroundSaturation: 1.15,
  foregroundBrightness: 1.05,
  backgroundTargetSaturation: 0.55,
  backgroundTargetBrightness: 0.85,
  backgroundColorizeStrength: 0.75,
  liquifyAmount: 0.0072,
  liquifyScale: 5,
  liquifySpeed: 0.6,
};

const ShaderPlane: React.FC<{
  colorTexture: THREE.Texture;
  maskTexture: THREE.Texture;
  backgroundTargetHueDeg: number;
  time: number;
  params: Omit<ForegroundPopProps, "src" | "maskSrc" | "backgroundHues">;
}> = ({ colorTexture, maskTexture, backgroundTargetHueDeg, time, params }) => {
  const advance = useThree((state) => state.advance);
  const { isRendering } = getRemotionEnvironment();

  const material = useMemo(
    () =>
      new THREE.ShaderMaterial({
        vertexShader,
        fragmentShader,
        uniforms: {
          uColorTexture: { value: null as THREE.Texture | null },
          uMaskTexture: { value: null as THREE.Texture | null },
          uForegroundSaturation: { value: 1 },
          uForegroundBrightness: { value: 1 },
          uBackgroundTargetHue: { value: 0 },
          uBackgroundTargetSaturation: { value: 0 },
          uBackgroundTargetBrightness: { value: 0 },
          uBackgroundColorizeStrength: { value: 0 },
          uTime: { value: 0 },
          uLiquifyAmount: { value: 0 },
          uLiquifyScale: { value: 1 },
          uLiquifySpeed: { value: 1 },
        },
      }),
    [],
  );

  material.uniforms.uColorTexture.value = colorTexture;
  material.uniforms.uMaskTexture.value = maskTexture;
  material.uniforms.uForegroundSaturation.value = params.foregroundSaturation;
  material.uniforms.uForegroundBrightness.value = params.foregroundBrightness;
  material.uniforms.uBackgroundTargetHue.value = backgroundTargetHueDeg;
  material.uniforms.uBackgroundTargetSaturation.value =
    params.backgroundTargetSaturation;
  material.uniforms.uBackgroundTargetBrightness.value =
    params.backgroundTargetBrightness;
  material.uniforms.uBackgroundColorizeStrength.value =
    params.backgroundColorizeStrength;
  material.uniforms.uTime.value = time;
  material.uniforms.uLiquifyAmount.value = params.liquifyAmount;
  material.uniforms.uLiquifyScale.value = params.liquifyScale;
  material.uniforms.uLiquifySpeed.value = params.liquifySpeed;

  // See SelectiveDesaturation.tsx for why this manual advance is necessary:
  // <ThreeCanvas> draws once per frame change, but the async video textures
  // resolve after that draw during rendering, so we force a second draw.
  useLayoutEffect(() => {
    if (isRendering) {
      advance(performance.now());
    }
  });

  return (
    <mesh frustumCulled={false}>
      <planeGeometry args={[2, 2]} />
      <primitive object={material} attach="material" />
    </mesh>
  );
};

const RenderScene: React.FC<{
  src: string;
  maskSrc: string;
  backgroundTargetHueDeg: number;
  time: number;
  params: Omit<ForegroundPopProps, "src" | "maskSrc" | "backgroundHues">;
}> = ({ src, maskSrc, backgroundTargetHueDeg, time, params }) => {
  const colorTexture = useOffthreadVideoTexture({ src });
  const maskTexture = useOffthreadVideoTexture({ src: maskSrc });
  if (!colorTexture || !maskTexture) {
    return null;
  }
  return (
    <ShaderPlane
      colorTexture={colorTexture}
      maskTexture={maskTexture}
      backgroundTargetHueDeg={backgroundTargetHueDeg}
      time={time}
      params={params}
    />
  );
};

const PreviewScene: React.FC<{
  src: string;
  maskSrc: string;
  width: number;
  height: number;
  backgroundTargetHueDeg: number;
  time: number;
  params: Omit<ForegroundPopProps, "src" | "maskSrc" | "backgroundHues">;
}> = ({ src, maskSrc, width, height, backgroundTargetHueDeg, time, params }) => {
  const colorRef = useRef<HTMLVideoElement>(null);
  const maskRef = useRef<HTMLVideoElement>(null);
  const colorTexture = useVideoTexture(colorRef);
  const maskTexture = useVideoTexture(maskRef);
  return (
    <>
      <Video
        ref={colorRef}
        src={src}
        muted
        style={{ position: "absolute", opacity: 0, width: 1, height: 1 }}
      />
      <Video
        ref={maskRef}
        src={maskSrc}
        muted
        style={{ position: "absolute", opacity: 0, width: 1, height: 1 }}
      />
      {colorTexture && maskTexture ? (
        <ThreeCanvas width={width} height={height}>
          <ShaderPlane
            colorTexture={colorTexture}
            maskTexture={maskTexture}
            backgroundTargetHueDeg={backgroundTargetHueDeg}
            time={time}
            params={params}
          />
        </ThreeCanvas>
      ) : null}
    </>
  );
};

export const ForegroundPop: React.FC<ForegroundPopProps> = ({
  src,
  maskSrc,
  backgroundHues,
  ...params
}) => {
  const { width, height, fps } = useVideoConfig();
  const frame = useCurrentFrame();
  const resolvedSrc = src.startsWith("http") ? src : staticFile(src);
  const resolvedMaskSrc = maskSrc.startsWith("http")
    ? maskSrc
    : staticFile(maskSrc);
  const isRendering = getRemotionEnvironment().isRendering;

  const backgroundTargetHueDeg =
    backgroundHues[Math.min(frame, backgroundHues.length - 1)] ?? 210;
  const time = frame / fps;

  return (
    <AbsoluteFill style={{ backgroundColor: "black" }}>
      {isRendering ? (
        <ThreeCanvas width={width} height={height}>
          <RenderScene
            src={resolvedSrc}
            maskSrc={resolvedMaskSrc}
            backgroundTargetHueDeg={backgroundTargetHueDeg}
            time={time}
            params={params}
          />
        </ThreeCanvas>
      ) : (
        <PreviewScene
          src={resolvedSrc}
          maskSrc={resolvedMaskSrc}
          width={width}
          height={height}
          backgroundTargetHueDeg={backgroundTargetHueDeg}
          time={time}
          params={params}
        />
      )}
    </AbsoluteFill>
  );
};
