import React, { useLayoutEffect, useMemo, useRef } from "react";
import * as THREE from "three";
import { useThree } from "@react-three/fiber";
import {
  AbsoluteFill,
  Video,
  getRemotionEnvironment,
  staticFile,
  useVideoConfig,
} from "remotion";
import {
  ThreeCanvas,
  useOffthreadVideoTexture,
  useVideoTexture,
} from "@remotion/three";
import { fragmentShader, vertexShader } from "./foregroundPopShader";

/**
 * Boosts saturation/brightness on the foreground subject and mutes (but does
 * NOT fully desaturate) the background, using a precomputed person-
 * segmentation matte (public/mask.mp4, generated by scripts/generate-mask.js)
 * instead of a color-based mask. See README.md for how to regenerate the
 * matte if you swap in a different source video.
 */
export type ForegroundPopProps = {
  src: string;
  maskSrc: string;
  /** Foreground saturation multiplier. 1 = unchanged, >1 = more vivid. */
  foregroundSaturation: number;
  /** Foreground brightness multiplier. 1 = unchanged, >1 = brighter. */
  foregroundBrightness: number;
  /** Background saturation multiplier. 1 = unchanged, 0 = fully gray. */
  backgroundSaturation: number;
  /** Background brightness multiplier. 1 = unchanged, <1 = dimmer. */
  backgroundBrightness: number;
};

/** Sensible defaults: subject pops, background is muted but still has color. */
export const defaultForegroundPopProps: Omit<
  ForegroundPopProps,
  "src" | "maskSrc"
> = {
  foregroundSaturation: 1.25,
  foregroundBrightness: 1.08,
  backgroundSaturation: 0.35,
  backgroundBrightness: 0.8,
};

const ShaderPlane: React.FC<{
  colorTexture: THREE.Texture;
  maskTexture: THREE.Texture;
  params: Omit<ForegroundPopProps, "src" | "maskSrc">;
}> = ({ colorTexture, maskTexture, params }) => {
  const advance = useThree((state) => state.advance);
  const { isRendering } = getRemotionEnvironment();

  const material = useMemo(
    () =>
      new THREE.ShaderMaterial({
        vertexShader,
        fragmentShader,
        uniforms: {
          uColorTexture: { value: null as THREE.Texture | null },
          uMaskTexture: { value: null as THREE.Texture | null },
          uForegroundSaturation: { value: 1 },
          uForegroundBrightness: { value: 1 },
          uBackgroundSaturation: { value: 1 },
          uBackgroundBrightness: { value: 1 },
        },
      }),
    [],
  );

  material.uniforms.uColorTexture.value = colorTexture;
  material.uniforms.uMaskTexture.value = maskTexture;
  material.uniforms.uForegroundSaturation.value = params.foregroundSaturation;
  material.uniforms.uForegroundBrightness.value = params.foregroundBrightness;
  material.uniforms.uBackgroundSaturation.value = params.backgroundSaturation;
  material.uniforms.uBackgroundBrightness.value = params.backgroundBrightness;

  // See SelectiveDesaturation.tsx for why this manual advance is necessary:
  // <ThreeCanvas> draws once per frame change, but the async video textures
  // resolve after that draw during rendering, so we force a second draw.
  useLayoutEffect(() => {
    if (isRendering) {
      advance(performance.now());
    }
  });

  return (
    <mesh frustumCulled={false}>
      <planeGeometry args={[2, 2]} />
      <primitive object={material} attach="material" />
    </mesh>
  );
};

const RenderScene: React.FC<{
  src: string;
  maskSrc: string;
  params: Omit<ForegroundPopProps, "src" | "maskSrc">;
}> = ({ src, maskSrc, params }) => {
  const colorTexture = useOffthreadVideoTexture({ src });
  const maskTexture = useOffthreadVideoTexture({ src: maskSrc });
  if (!colorTexture || !maskTexture) {
    return null;
  }
  return (
    <ShaderPlane
      colorTexture={colorTexture}
      maskTexture={maskTexture}
      params={params}
    />
  );
};

const PreviewScene: React.FC<{
  src: string;
  maskSrc: string;
  width: number;
  height: number;
  params: Omit<ForegroundPopProps, "src" | "maskSrc">;
}> = ({ src, maskSrc, width, height, params }) => {
  const colorRef = useRef<HTMLVideoElement>(null);
  const maskRef = useRef<HTMLVideoElement>(null);
  const colorTexture = useVideoTexture(colorRef);
  const maskTexture = useVideoTexture(maskRef);
  return (
    <>
      <Video
        ref={colorRef}
        src={src}
        muted
        style={{ position: "absolute", opacity: 0, width: 1, height: 1 }}
      />
      <Video
        ref={maskRef}
        src={maskSrc}
        muted
        style={{ position: "absolute", opacity: 0, width: 1, height: 1 }}
      />
      {colorTexture && maskTexture ? (
        <ThreeCanvas width={width} height={height}>
          <ShaderPlane
            colorTexture={colorTexture}
            maskTexture={maskTexture}
            params={params}
          />
        </ThreeCanvas>
      ) : null}
    </>
  );
};

export const ForegroundPop: React.FC<ForegroundPopProps> = ({
  src,
  maskSrc,
  ...params
}) => {
  const { width, height } = useVideoConfig();
  const resolvedSrc = src.startsWith("http") ? src : staticFile(src);
  const resolvedMaskSrc = maskSrc.startsWith("http")
    ? maskSrc
    : staticFile(maskSrc);
  const isRendering = getRemotionEnvironment().isRendering;

  return (
    <AbsoluteFill style={{ backgroundColor: "black" }}>
      {isRendering ? (
        <ThreeCanvas width={width} height={height}>
          <RenderScene
            src={resolvedSrc}
            maskSrc={resolvedMaskSrc}
            params={params}
          />
        </ThreeCanvas>
      ) : (
        <PreviewScene
          src={resolvedSrc}
          maskSrc={resolvedMaskSrc}
          width={width}
          height={height}
          params={params}
        />
      )}
    </AbsoluteFill>
  );
};
